name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    L1_LANDING:
      +schema: L1_LANDING_DEV
      +materialized: table
    L2_PROCESSING:
      +schema: L2_PROCESSING_DEV
      +materialized: table
    L3_CONSUMPTION:
      +schema: L3_CONSUMPTION_DEV
      +materialized: table


